name: Tests

on:
    push:
        branches:
            - main
        paths:
            - 'Sources/**'
            - 'Tests/**'
            - 'Package.swift'
            - 'Package.resolved'
    pull_request:
        branches:
            - main
        paths:
            - 'Sources/**'
            - 'Tests/**'
            - 'Package.swift'
            - 'Package.resolved'

jobs:
    build:
        name: Test on ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: swift-actions/setup-swift@v2
              with:
                swift-version: '6'
            - name: Build
              run: swift build -v -c release --skip-update
            - name: Run tests
              run: swift test -v -c release
