name: Tests

on:
    push:
        branches:
            - main
        paths:
            - 'Sources/**'
            - 'Tests/**'
            - 'Package.swift'
            - 'Package.resolved'
            - '.github/workflows/build_test.yml'
    pull_request:
        branches:
            - main
        paths:
            - 'Sources/**'
            - 'Tests/**'
            - 'Package.swift'
            - 'Package.resolved'

jobs:
    build:
        name: Test on ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-15]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Build
              run: swift build -v
            - name: Run tests
              run: swift test -v
